global:
  c4ghPath: c4gh
  jwtPath: jwt
  tlsPath: tls
  podSecurityPolicy:
    create: false
  archive:
    storageType: posix
    existingClaim: archive-volume
    volumePath: "/archive"
  backupArchive:
    storageType: posix
    existingClaim: backup-volume
    volumePath: "/backup"
  broker:
    host: "broker-sda-mq"
    exchange: "sda"
    port: 5671
    verifyPeer: true
    password: "admin"
    username: "admin"
    backupRoutingKey: "backup"
  cega:
    host: "cega-users"
    user: "legatest"
  db:
    host: "postgres-sda-db"
  elixir:
    pubKey: "token.pub"
  inbox:
    storageType: posix
    path: "/inbox"
    user: "lega"
    existingClaim: inbox-volume
  logLevel: debug
backup:
  deploy: true
