global:
  c4ghPath: c4gh
  jwtPath: jwt
  tlsPath: tls
  podSecurityPolicy:
    create: false
  archive:
    storageType: s3
    s3Url: "https://minio"
    s3Bucket: "archive"
    s3CaFile: "ca.crt"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
  auth:
    elixirID: DfCieZLuBU
    elixirSecret: DfCieZLuBU
    jwtKey: jwt.key
    jwtPub: token.pub
    useTLS: true
  backupArchive:
    storageType: s3
    s3Url: "https://minio"
    s3Bucket: "backup"
    s3CaFile: "ca.crt"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
  broker:
    host: "broker-sda-mq"
    exchange: "sda"
    port: 5671
    verifyPeer: true
    password: "admin"
    username: "admin"
    backupRoutingKey: "backup"
  cega:
    host: "cega-users"
    user: "legatest"
    password: 3iSGc5loLN7hu2EwT2Z2CzCT26iUrk3t
  db:
    host: "postgres-sda-db"
  c4gh:
    file: c4gh.key
    passphrase: oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm
    publicFile: "c4gh.pub"
  elixir:
    pubKey: token.pub
    oidcdHost: "http://oidc-server:8080"
    jwkPath: ""
  inbox:
    storageType: s3
    # existingClaim: test
    s3Url: "https://minio"
    s3Bucket: "archive"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
    s3CaFile: ca.crt
    s3ReadyPath: "/minio/health/ready"
  ingress:
    hostName:
      auth: sda-sda-svc-auth
  logLevel: debug
backup:
  deploy: true
