---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-test-certs"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  {{- (.Files.Glob "files/{tester,ca}*").AsSecrets | nindent 2 }}

