apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}
data:
  pgInPasswd: {{ include "pgInPassword" . | b64enc }}
  pgOutPasswd: {{ include "pgOutPassword" . | b64enc }}
{{- if not .Values.externalPkiService.tlsPath }}
{{- $dbcerts := .Files.Glob "files/pg.*" }}
{{- $cacert := .Files.Glob "files/ca.crt" }}
{{- if $cacert }}
{{ ( $cacert).AsSecrets | indent 2 }}
{{- end  }}
{{- if $dbcerts }}
{{ ( $dbcerts ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
