{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "sda.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Expand the name of the chart.
*/}}
{{- define "sda.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "sda.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "tlsPath" -}}
    {{- if .Values.pkiService.enabled }}
        {{- printf "%s" (regexReplaceAll "/$"  (required "pkiService.tlsPath is required if pkiservice is enabled" .Values.pkiService.tlsPath) "" ) -}}
    {{- else }}
        {{- printf "/tls/certs" }}
    {{- end -}}    
{{- end -}}

{{/**/}}
{{- define "mqPass" -}}
{{- .Values.broker.password -}}
{{- end -}}

{{- define "orchCert" -}}
    {{- if .Values.pkiService.enabled }}
        {{- printf "%s" (regexReplaceAll "^/*|/+" (printf "%s/%s" .Values.pkiService.tlsPath (required "a TLS certificate is required" .Values.tls.cert)) "/")}}
    {{- else }}
        {{- printf "/tls/certs/%s" (required "a TLS certificate is required" .Values.tls.cert)}}
    {{- end -}}
{{- end -}}

{{- define "orchKey" -}}
    {{- if .Values.pkiService.enabled }}
        {{- printf "%s" (regexReplaceAll "^/*|/+" (printf "%s/%s" .Values.pkiService.tlsPath (required "a TLS key is required" .Values.tls.key)) "/")}}
    {{- else }}
        {{- printf "/tls/certs/%s" (required "a TLS key is required" .Values.tls.key)}}
    {{- end -}}
{{- end -}}

{{- define "caCert" -}}
    {{- if .Values.pkiService.enabled }}
        {{- printf "%s" (regexReplaceAll "^/*|/+" (printf "%s/%s" .Values.pkiService.tlsPath (required "a CA certificate is required" .Values.tls.caCert)) "/")}}
    {{- else }}
        {{- printf "/tls/certs/%s" (required "a CA certificate is required" .Values.tls.caCert) }}
    {{- end -}}
{{- end -}}
