---
{{- define "mqfullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  resourceVersion: {{ template "mqfullname" . }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  containers:
    - name: {{ .Release.Name }}-test
      {{- if .Values.global.tls.enabled }}
      image: "{{ .Values.testimage.repository }}:{{ .Values.testimage.tag }}"
      {{- else }}
      image: "subfuzion/netcat:latest"
      {{- end }}
      imagePullPolicy: {{ .Values.testimage.pullPolicy | quote }}
      volumeMounts:
      {{- if and .Values.global.tls.enabled (not .Values.externalPkiService.tlsPath) }}
        - name: certs
          mountPath: /certs
      {{- end }}
      env:
        {{- if .Values.externalPkiService.tlsPath }}
        - name: PKI_VOLUME_PATH
          value: {{ .Values.externalPkiService.tlsPath }}
        {{- end }}
        - name: MQ_HOST
          value: {{ template "mqfullname" . }}
      command: [ "/bin/sh" ]
      args:
        - "-x"
        - "-c"
        {{- if .Values.global.tls.enabled }}
        - 'P=${PKI_VOLUME_PATH:-/certs}; 
           count=1;
           until openssl s_client -connect "${MQ_HOST}:5671" -verify 50 -key "$P/{{ .Values.testimage.tls.tlsKey }}" -cert "$P/{{ .Values.testimage.tls.tlsCert }}" -verify_return_error -CAfile "$P/{{ .Values.testimage.tls.caCert }}" </dev/null; do
             sleep 5;
             count=$((count+1));
             if [ "$count" -gt 10 ]; then
               exit 1;
             fi;
           done;
           exit 0'
        {{- else }}
        - 'count=1;
          until nc -zvw10 ${MQ_HOST} 5672 </dev/null; do
             sleep 5;
             count=$((count+1));
             if [ "$count" -gt 10 ]; then
               exit 1;
             fi;
           done;
           exit 0'
        {{- end }}
  {{- if and .Values.global.tls.enabled (not .Values.externalPkiService.tlsPath) }}
  volumes:
      - name: certs
        secret:
          secretName: {{ required "TLS secret name is required when TLS in enabled" .Values.testimage.tls.secretName }}
    {{- end }}
  restartPolicy: Never

