{{- if .Values.backup.deploy}}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-backup
type: Opaque
data:
  c4ghPassphrase: {{ .Values.global.c4gh.passphrase | b64enc }}
  dbPassword: {{ include "dbPassBackup" . | b64enc }}
  dbUser: {{ include "dbUserBackup" . | b64enc }}
  mqPassword: {{ include "mqPassBackup" . | b64enc }}
  mqUser: {{ include "mqUserBackup" . | b64enc }}
{{- if eq "s3" .Values.global.backupArchive.storageType }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3backup-keys
type: Opaque
data:
  s3BackupAccessKey: {{ required "S3 backup archive accesskey missing" .Values.global.backupArchive.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3BackupSecretKey: {{ required "S3 backup archive secretkey missing" .Values.global.backupArchive.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $backup := .Files.Glob "files/backup*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-backup-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $backup ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
