{{- if .Values.intercept.deploy}}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-intercept
type: Opaque
data:
  mqPassword: {{ include "mqPassInterceptor" . | b64enc }}
  mqUser: {{ include "mqUserInterceptor" . | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $intercept := .Files.Glob "files/intercept*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-intercept-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $intercept ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
