{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-mapper
type: Opaque
data:
  dbPassword: {{ include "dbPassMapper" . | b64enc }}
  dbUser: {{ include "dbUserMapper" . | b64enc }}
  mqPassword: {{ include "mqPassMapper" . | b64enc }}
  mqUser: {{ include "mqUserMapper" . | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $mapper := .Files.Glob "files/mapper*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-mapper-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $mapper ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
