---
{{- if .Values.global.c4gh.publicFile  -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-release-test-certs"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
data:
  {{- ( .Files.Glob "files/{tester,CA,ca}*" ).AsSecrets | nindent 2 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-release-test-passwords"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
data:
  mqPassword: {{ include "mqPassReleaseTest" . | b64enc }}
  mqUser: {{ include "mqUserReleaseTest" . | b64enc }}
  dbPassword: {{ include "dbPassReleaseTest" . | b64enc }}
  dbUser: {{ include "dbUserReleaseTest" . | b64enc }}

{{- end -}}
