{{- if not .Values.global.vaultSecrets }}
{{- $c4ghFile := .Files.Glob (printf "files/%s" .Values.global.c4gh.file) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-c4gh
data:
{{ ( $c4ghFile ).AsSecrets | trim | indent 2 }}
  passphrase: {{ required "crypt4gh passphrase is missing" .Values.global.c4gh.passphrase | quote | trimall "\"" | b64enc }}
{{- if and .Values.global.archive.s3AccessKey .Values.global.archive.s3SecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3archive-keys
type: Opaque
data:
  s3ArchiveAccessKey: {{ .Values.global.archive.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3ArchiveSecretKey: {{ .Values.global.archive.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if and .Values.global.inbox.s3AccessKey .Values.global.inbox.s3SecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3inbox-keys
type: Opaque
data:
  s3InboxAccessKey: {{ .Values.global.inbox.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3InboxSecretKey: {{ .Values.global.inbox.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- end }}
