
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-verify
type: Opaque
data:
  c4ghPassphrase: {{ .Values.global.c4gh.passphrase | b64enc }}
  dbPassword: {{ include "dbPassVerify" . | b64enc }}
  dbUser: {{ include "dbUserVerify" . | b64enc }}
  mqPassword: {{ include "mqPassVerify" . | b64enc }}
  mqUser: {{ include "mqUserVerify" . | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $verify := .Files.Glob "files/verify*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-verify-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $verify ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
