name: Scripts linter

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
